apiVersion: v1
kind: Service
metadata:
  name: orbiter8-client-staging
  namespace: websites
  labels:
    app: orbiter8-client
    stage: staging
    site: staging.orbiter8.com
spec:
  type: ClusterIP
  selector:
    app: orbiter8-client
  ports:
    - port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbiter8-client-staging
  namespace: websites
  labels:
    app: orbiter8-client
    stage: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbiter8-client
  template:
    metadata:
      labels:
        app: orbiter8-client
    spec:
      imagePullSecrets:
        - name: partavate-gitlab-registry
      containers:
        - name: orbiter8-client
          image: registry.gitlab.com/partavate/prototype/orbiter8-client:3.0.2
          imagePullPolicy: "Always"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /nginx-health
              port: 80
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              memory: '32Mi'
              cpu: '25m'
            limits:
              memory: '250Mi'
              cpu: '500m'
          ports:
            - containerPort: 80

